/*
CREATE DOMAIN CRS_ID BIGINT;
CREATE DOMAIN CRS_NAME VARCHAR(128);
CREATE DOMAIN CRS_PHONE VARCHAR(128);
CREATE DOMAIN CRS_ADDRESS VARCHAR(128);
CREATE DOMAIN CRS_EMAIL VARCHAR(256);
CREATE DOMAIN CRS_PASSWORD VARCHAR(1024);
CREATE DOMAIN CRS_DESCRIPTION VARCHAR(2048);
CREATE DOMAIN CRS_CURRENCY DECIMAL(19,4);
*/

CREATE TABLE creditcard (

    creditcard_id CRS_ID PRIMARY KEY,
    creditcardnr CRS_PASSWORD, --encrypted like 
	cc_name CRS_NAME,
	cc_lastname CRS_NAME,
    customerid CRS_ID --Added as a part of unitofwork 
);
